spring:
  thymeleaf:
    enabled: false
  freemarker:
    enabled: false
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false
  flyway:
    enabled: false
  main:
    web-application-type: NONE
  datasource:
    continue-on-error: true
    url: ${dump.url}
    username: ${dump.username}
    password: ${dump.password}
    driver-class-name: ${dump.driver-class-name}
    sql-script-encoding: UTF-8
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      auto-commit: false
      maximum-pool-size: 1
      minimum-idle: 0
      read-only: false
  batch:
    initializer:
      enabled: false
    enable: true
    job:
      names: dumpJob
logging:
  level:
    root: INFO
    org.netf.evidb.dump.batch: INFO
    org.springframework.jdbc.datasource.DataSourceTransactionManager: TRACE
    org.springframework.jdbc.core.JdbcTemplate: TRACE